# Generated by Django 6.0.1 on 2026-03-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_webhook_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
