# Generated by Django 6.0.1 on 2026-03-03 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_tasklog_screenshot_savinggoal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GachaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.IntegerField(default=0)),
                ("tickets", models.IntegerField(default=0)),
                ("pity_stack", models.IntegerField(default=0)),
                ("is_guaranteed", models.BooleanField(default=False)),
                ("has_monthly_pass", models.BooleanField(default=True)),
                ("tower_avg_stars", models.IntegerField(default=800)),
                ("ruins_avg_reward", models.IntegerField(default=800)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scheduler.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
