# Generated by Django 6.0.1 on 2026-03-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_gachaprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gachaprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="savinggoal",
            name="user",
        ),
        migrations.RemoveField(
            model_name="spending",
            name="user",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.RemoveField(
            model_name="tasklog",
            name="user",
        ),
    ]
