# Generated by Django 6.0.1 on 2026-03-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_gachaprofile_user_savinggoal_user_spending_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklog",
            name="screenshot",
        ),
    ]
